# Permalinks
permalink:           pretty

# Setup
title:               Xinxin Jiang
tagline:             Date Science Run.d and Run.d
url:                 http://Xinxin-Jiang.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Xinxin Jiang
  email:             toruntoruntorunto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Xinxin-Jiang

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
